prjC349WebMVC/Controllers/RVI_CreateWithEPSLOGController.cs
using MySql.Data.MySqlClient;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;
using prjC349WebMVC.Models;
using System.Data;
using PagedList;
using NPOI.HSSF.UserModel;
using NPOI.SS.UserModel;
using NPOI.SS.Util;
using System.IO;
using NPOI.XSSF.UserModel;
using MySqlX.XDevAPI.Common;

namespace prjC349WebMVC.Controllers
{
    public class RVI_CreateWithEPSLOGController : Controller
    {
        string connStr = WebConfigurationManager.ConnectionStrings["c349ConnectionString"].ConnectionString;
        int pageSize = 10;
        public ActionResult Index(string queryMonth, int page = 1)
        {
            //if (queryMonth == null)
            //{
            //    queryMonth = DateTime.Now.Month.ToString().PadLeft(2,'0')+"/"+ DateTime.Now.Year.ToString();
            //}
            ViewBag.Location = "Y423";
            ViewBag.queryMonth = queryMonth;
            int currentPage = page < 1 ? 1 : page;
            var result = GetAllRecrods(queryMonth,"Y423").ToPagedList(currentPage, pageSize);
            //ViewBag.Cookie = Request.Cookies.AllKeys[0];
            return View(result);
        }
        public ActionResult C349_1(string queryMonth, int page = 1)
        {
            ViewBag.queryMonth = queryMonth;
            int currentPage = page < 1 ? 1 : page;
            var result = GetAllRecrods(queryMonth,"C349_1").ToPagedList(currentPage, pageSize);
            //ViewBag.Cookie = Request.Cookies.AllKeys[0];
            return View(result);
        }
        public ActionResult C349_1_Detail(string id)
        {
            return View(GetRecrod(id));            
        }
        public ActionResult Create()
        {

            var selectList = new List<SelectListItem>()
            {
                new SelectListItem {Text="text-1", Value="value-1" },
                new SelectListItem {Text="text-2", Value="value-2" },
                new SelectListItem {Text="text-3", Value="value-3" },
            };

            //預設選擇哪一筆
            selectList.Where(q => q.Value == "value-2").First().Selected = true;

            ViewBag.SelectList = selectList;
            return View();
        }
        [HttpPost]
        public ActionResult Create(remote_visual_inspection remote_visual_inspection)
        {
            if (ModelState.IsValid)
            {
                ViewBag.Error = false;
                try
                {
                    MySqlCommand cmd = new MySqlCommand();
                    cmd.CommandText = "INSERT INTO remote_visual_inspection_epslog(tdate,carId,coil1,coil2,coil3,coil4,coil5,coil6,coil7,coil8,creator,updateTime,ip,location)" +
                        "VALUES(@tdate,@carId,@coil1,@coil2,@coil3,@coil4,@coil5,@coil6,@coil7,@coil8,@creator,@updateTime,@ip,@location)";
                    //cmd.Parameters.Add(new MySqlParameter("@id", MySqlDbType.VarChar)).Value = employee.id;
                    cmd.Parameters.Add(new MySqlParameter("@tdate", MySqlDbType.DateTime)).Value = remote_visual_inspection.tdate;
                    cmd.Parameters.Add(new MySqlParameter("@carId", MySqlDbType.VarChar)).Value = remote_visual_inspection.carId;
                    cmd.Parameters.Add(new MySqlParameter("@coil1", MySqlDbType.VarChar)).Value = remote_visual_inspection.coil1;
                    cmd.Parameters.Add(new MySqlParameter("@coil2", MySqlDbType.VarChar)).Value = remote_visual_inspection.coil2;
                    cmd.Parameters.Add(new MySqlParameter("@coil3", MySqlDbType.VarChar)).Value = remote_visual_inspection.coil3;
                    cmd.Parameters.Add(new MySqlParameter("@coil4", MySqlDbType.VarChar)).Value = remote_visual_inspection.coil4;
                    cmd.Parameters.Add(new MySqlParameter("@coil5", MySqlDbType.VarChar)).Value = remote_visual_inspection.coil5;
                    cmd.Parameters.Add(new MySqlParameter("@coil6", MySqlDbType.VarChar)).Value = remote_visual_inspection.coil6;
                    cmd.Parameters.Add(new MySqlParameter("@coil7", MySqlDbType.VarChar)).Value = remote_visual_inspection.coil7;
                    cmd.Parameters.Add(new MySqlParameter("@coil8", MySqlDbType.VarChar)).Value = remote_visual_inspection.coil8;


                    cmd.Parameters.Add(new MySqlParameter("@creator", MySqlDbType.VarChar)).Value = remote_visual_inspection.creator;
                    cmd.Parameters.Add(new MySqlParameter("@location", MySqlDbType.VarChar)).Value = remote_visual_inspection.location;

                    cmd.Parameters.Add(new MySqlParameter("@updateTime", MySqlDbType.DateTime)).Value = DateTime.Parse(remote_visual_inspection.tdate.ToString())
                        .AddHours(DateTime.Now.Hour).AddMinutes(DateTime.Now.Minute).AddSeconds(DateTime.Now.Second);
                    cmd.Parameters.Add(new MySqlParameter("@ip", MySqlDbType.VarChar)).Value = IPAddress.Get();
                    ExecuteCmd(cmd);
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    ViewBag.Error = true;
                    return View(remote_visual_inspection);
                }
            }
            return View(remote_visual_inspection);
        }
        public ActionResult Edit(string id)
        {

            return View(GetRecrod(id));
        }
        [HttpPost]
        public ActionResult Edit(remote_visual_inspection remote_visual_inspection)
        {
            if (ModelState.IsValid)
            {
                //MySqlCommand cmd = new MySqlCommand();

                //cmd.CommandText = "UPDATE remote_visual_inspection_epslog SET tdate=@tdate, carId=@carId,comment1=@comment1, comment2=@comment2, " +
                //    "coil1=@coil1, coil2=@coil2, coil3=@coil3, coil4=@coil4, coil5=@coil5, coil6=@coil6, coil7=@coil7 ,coil8=@coil8,updateTime=@updateTime WHERE id=@id";
                //cmd.Parameters.Add(new MySqlParameter("@id", MySqlDbType.VarChar)).Value = remote_visual_inspection.id;
                //cmd.Parameters.Add(new MySqlParameter("@tdate", MySqlDbType.Date)).Value = remote_visual_inspection.tdate;
                //cmd.Parameters.Add(new MySqlParameter("@carId", MySqlDbType.VarChar)).Value = remote_visual_inspection.carId;
                //cmd.Parameters.Add(new MySqlParameter("@comment1", MySqlDbType.VarChar)).Value = remote_visual_inspection.comment1;
                //cmd.Parameters.Add(new MySqlParameter("@comment2", MySqlDbType.VarChar)).Value = remote_visual_inspection.comment2;
                //cmd.Parameters.Add(new MySqlParameter("@coil1", MySqlDbType.VarChar)).Value = remote_visual_inspection.coil1;
                //cmd.Parameters.Add(new MySqlParameter("@coil2", MySqlDbType.VarChar)).Value = remote_visual_inspection.coil2;
                //cmd.Parameters.Add(new MySqlParameter("@coil3", MySqlDbType.VarChar)).Value = remote_visual_inspection.coil3;
                //cmd.Parameters.Add(new MySqlParameter("@coil4", MySqlDbType.VarChar)).Value = remote_visual_inspection.coil4;
                //cmd.Parameters.Add(new MySqlParameter("@coil5", MySqlDbType.VarChar)).Value = remote_visual_inspection.coil5;
                //cmd.Parameters.Add(new MySqlParameter("@coil6", MySqlDbType.VarChar)).Value = remote_visual_inspection.coil6;
                //cmd.Parameters.Add(new MySqlParameter("@coil7", MySqlDbType.VarChar)).Value = remote_visual_inspection.coil7;
                //cmd.Parameters.Add(new MySqlParameter("@coil8", MySqlDbType.VarChar)).Value = remote_visual_inspection.coil8;
                //cmd.Parameters.Add(new MySqlParameter("@updateTime", MySqlDbType.DateTime)).Value = DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss");
                //cmd.Parameters.Add(new MySqlParameter("@ip", MySqlDbType.VarChar)).Value = IPAddress.Get();

                MySqlConnection conn = new MySqlConnection(connStr);
                string SQL = "select count(*) from `c349`.`remote_visual_inspection_abnormal` where `t_date` = @t_date and `t_carId` = @t_carId";
                MySqlCommand cmd = new MySqlCommand(SQL, conn);
                cmd.Parameters.Add(new MySqlParameter("@t_date", MySqlDbType.DateTime)).Value = remote_visual_inspection.tdate;
                cmd.Parameters.Add(new MySqlParameter("@t_carId", MySqlDbType.VarChar)).Value = remote_visual_inspection.carId;
                cmd.Parameters.Add(new MySqlParameter("@t_comment", MySqlDbType.VarChar)).Value = remote_visual_inspection.comment1;



                MySqlDataAdapter adp = new MySqlDataAdapter(cmd);
                DataSet ds = new DataSet();
                adp.Fill(ds);
                DataTable dt = ds.Tables[0];
                if (dt.Rows[0]["count(*)"].ToString() != "0")
                {
                    //update
                    cmd.CommandText = "UPDATE remote_visual_inspection_abnormal SET t_comment=@t_comment where `t_date` = @t_date and `t_carId` = @t_carId";
                    ExecuteCmd(cmd);
                }
                else
                {
                    //create
                    cmd.CommandText = "INSERT INTO remote_visual_inspection_abnormal(t_date,t_carId,t_comment)" +
                            "VALUES(@t_date,@t_carId,@t_comment)";

                    ExecuteCmd(cmd);
                }


                //cmd.CommandText = "DELETE FROM remote_visual_inspection_abnormal WHERE t_date=@t_date AND t_carId=@t_carId";

                //ExecuteCmd(cmd);


                return RedirectToAction("Index");
            }
            return View(remote_visual_inspection);
        }
        public ActionResult Delete(string id)
        {
            MySqlCommand cmd = new MySqlCommand();
            cmd.CommandText = "DELETE FROM remote_visual_inspection_epslog WHERE id=@id";
            cmd.Parameters.Add(new MySqlParameter("@id", MySqlDbType.VarChar)).Value = id;

            ExecuteCmd(cmd);

prjC349WebMVC/Views/RVI_CreateWithEPSLOG/C349_1.cshtml
@model IPagedList<prjC349WebMVC.Models.remote_visual_inspection>
@using PagedList
@using PagedList.Mvc
@using System
@{
    ViewBag.Title = "C349_1車道檢放管理";
}

<h1>@ViewBag.Cookie</h1>

<link href="~/Content/PagedList.css" rel="stylesheet" />

<h2>@ViewBag.Title</h2>

<br />
<br />
<form method="get" action="~/RVI_CreateWithEPSLOG/C349_1">
    <input type="text" name="queryMonth" id="tbMonth" value="@ViewBag.queryMonth" />
    <input type="submit" value="查詢其他月份" />
</form>
@section scripts{
    <link rel="stylesheet" href="~/Scripts/jquery-ui-1.13.1.custom/jquery-ui.css">
    <script src="~/Scripts/jquery-ui-1.13.1.custom/jquery-ui.js"></script>
    <script src="~/Scripts/jquery-ui-1.13.1.custom/jquery.mtz.monthpicker.js"></script>
    <script>
        $(function () {
            $("#tbMonth").monthpicker({ monthNames: ['一月', '二月', '三月', '四月', '五月', '六月', '七月', '八月', '九月', '十月', '十一月', '十二月'] });
        });
    </script>
}

<br />
<p>
    @*@Html.ActionLink("新增", "Create", "", new { @class = "btn btn-primary" })*@
    @{ViewBag.Location = "C349_1"; }
    <input type="button" onclick="location.href='@Url.Action("ExporttoExcel", "RVI_CreateWithEPSLOG")'" value="匯出EXCEL" class="btn btn-success" />
</p>
@if (Model.Count() == 0)
{

    <div class="alert alert-info">
        <strong>無檢放紀錄</strong>
    </div>
}
else
{
    <label>共計檢放 @ViewBag.Count 車次</label>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().tdate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().carId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().comment1)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().coil1)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().coil2)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().coil3)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().coil4)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().coil5)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().coil6)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().coil7)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().coil8)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().creator)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().updateTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().ip)
            </th>
            <th></th>
        </tr>



        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelitem => item.id)
                </td>
                <td>
                    @Html.DisplayFor(modelitem => item.tdate)
                </td>
                <td>
                    @Html.DisplayFor(modelitem => item.carId)
                </td>
                <td>
                    @Html.DisplayFor(modelitem => item.comment1)
                </td>
                <td>
                    @Html.DisplayFor(modelitem => item.coil1)
                </td>
                <td>
                    @Html.DisplayFor(modelitem => item.coil2)
                </td>
                <td>
                    @Html.DisplayFor(modelitem => item.coil3)
                </td>
                <td>
                    @Html.DisplayFor(modelitem => item.coil4)
                </td>
                <td>
                    @Html.DisplayFor(modelitem => item.coil5)
                </td>
                <td>
                    @Html.DisplayFor(modelitem => item.coil6)
                </td>
                <td>
                    @Html.DisplayFor(modelitem => item.coil7)
                </td>
                <td>
                    @Html.DisplayFor(modelitem => item.coil8)
                </td>
                <td>
                    @Html.DisplayFor(modelitem => item.creator)
                </td>
                <td>
                    @Html.DisplayFor(modelitem => item.updateTime)
                </td>
                <td>
                    @Html.DisplayFor(modelitem => item.ip)
                </td>

                <td>
                    <a href="@Url.Action("Edit")?id=@item.id" class="btn btn-warning">編輯</a>
                    @{
                        try
                        {
                            if (prjC349WebMVC.IPAddress.Get() == "::1" || Request.Cookies["uid"].Value == "224485" || Request.Cookies["uid"].Value == "214585" || Request.Cookies["uid"].Value == "197459")
                            {
                                <a href="@Url.Action("Delete")?id=@item.id" class="btn btn-danger" onclick="return confirm('確定要刪除編號 @item.id 的員工紀錄嗎?');">刪除</a>
                            }
                        }
                        catch
                        {

                        }

                    }


                </td>
            </tr>
            <tr>
                @{
                    string photosUrl = "http://10.10.119.14/Photos/";
                    int i = 0;
                    string str_i = i.ToString().PadLeft(2, '0');
                    string camlnk = $"{photosUrl}{item.tdate.Value.ToString("yyyyMMdd_HHmmss")}_{Uri.EscapeUriString(item.carId.ToString())}/{item.tdate.Value.ToString("yyyyMMdd_HHmmss")}_{Uri.EscapeUriString(item.carId.ToString())}_cam{str_i}.jpeg";
                    <td colspan="10">
                        <a href=@Url.Action("Edit") ?id=@item.id>
                            <img src=@camlnk style="width:96px;height:54px" />
                        </a>
                    </td>

                }
            </tr>
        }

    </table>
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page, queryMonth = ViewBag.queryMonth }))
}

prjC349WebMVC/Views/RVI_CreateWithEPSLOG/Index.cshtml
@model IPagedList<prjC349WebMVC.Models.remote_visual_inspection>
@using PagedList
@using PagedList.Mvc
@using System
@{
    ViewBag.Title = "遠端檢放管理";
}

<h1>@ViewBag.Cookie</h1>

<link href="~/Content/PagedList.css" rel="stylesheet" />

<h2>遠端檢放管理</h2>

<br />
<br />
<form method="get" action="~/RVI_CreateWithEPSLOG/Index">
    <input type="text" name="queryMonth" id="tbMonth" value="@ViewBag.queryMonth" />
    <input type="submit" value="查詢其他月份" />
</form>
@section scripts{
    <link rel="stylesheet" href="~/Scripts/jquery-ui-1.13.1.custom/jquery-ui.css">
    <script src="~/Scripts/jquery-ui-1.13.1.custom/jquery-ui.js"></script>
    <script src="~/Scripts/jquery-ui-1.13.1.custom/jquery.mtz.monthpicker.js"></script>
    <script>
        $(function () {
            $("#tbMonth").monthpicker({ monthNames: ['一月', '二月', '三月', '四月', '五月', '六月', '七月', '八月', '九月', '十月', '十一月', '十二月'] });
        });
    </script>
}

<br />
<p>
    @*@Html.ActionLink("新增", "Create", "", new { @class = "btn btn-primary" })*@    

        <input type="button" onclick="location.href='@Url.Action("ExporttoExcel", "RVI_CreateWithEPSLOG")?location=@ViewBag.Location'" value="匯出EXCEL" class="btn btn-success" />
</p>
@if (Model.Count() == 0)
{

    <div class="alert alert-info">
        <strong>無遠端檢放紀錄</strong>
    </div>
}
else
{
    <label>共計檢放 @ViewBag.Count 車次</label>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().tdate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().carId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().comment1)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().coil1)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().coil2)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().coil3)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().coil4)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().coil5)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().coil6)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().coil7)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().coil8)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().creator)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().updateTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().ip)
            </th>
            <th></th>
        </tr>



        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelitem => item.id)
                </td>
                <td>
                    @Html.DisplayFor(modelitem => item.tdate)
                </td>
                <td>
                    @Html.DisplayFor(modelitem => item.carId)
                </td>
                <td>
                    @Html.DisplayFor(modelitem => item.comment1)
                </td>
                <td>
                    @Html.DisplayFor(modelitem => item.coil1)
                </td>
                <td>
                    @Html.DisplayFor(modelitem => item.coil2)
                </td>
                <td>
                    @Html.DisplayFor(modelitem => item.coil3)
                </td>
                <td>
                    @Html.DisplayFor(modelitem => item.coil4)
                </td>
                <td>
                    @Html.DisplayFor(modelitem => item.coil5)
                </td>
                <td>
                    @Html.DisplayFor(modelitem => item.coil6)
                </td>
                <td>
                    @Html.DisplayFor(modelitem => item.coil7)
                </td>
                <td>
                    @Html.DisplayFor(modelitem => item.coil8)
                </td>
                <td>
                    @Html.DisplayFor(modelitem => item.creator)
                </td>
                <td>
                    @Html.DisplayFor(modelitem => item.updateTime)
                </td>
                <td>
                    @Html.DisplayFor(modelitem => item.ip)
                </td>

                <td>
                    <a href="@Url.Action("Edit")?id=@item.id" class="btn btn-warning">編輯</a>
                    @{
                        try
                        {
                            if (prjC349WebMVC.IPAddress.Get() == "::1" || Request.Cookies["uid"].Value == "224485" || Request.Cookies["uid"].Value == "214585" || Request.Cookies["uid"].Value == "197459")
                            {
                                <a href="@Url.Action("Delete")?id=@item.id" class="btn btn-danger" onclick="return confirm('確定要刪除編號 @item.id 的員工紀錄嗎?');">刪除</a>
                            }
                        }
                        catch
                        {

                        }

                    }


                </td>
            </tr>
            <tr>
                @{
                    string photosUrl = "http://10.10.102.14/Photos/";
                    int i = 13;
                    string str_i = i.ToString();
                    string camlnk = $"{photosUrl}{item.tdate.Value.ToString("yyyyMMdd_HHmmss")}_{Uri.EscapeUriString(item.carId.ToString())}/{item.tdate.Value.ToString("yyyyMMdd_HHmmss")}_{Uri.EscapeUriString(item.carId.ToString())}_cam{str_i}.jpeg";
                    <td colspan="10">
                        <a href=@Url.Action("Edit")?id=@item.id>
                            <img src=@camlnk style="width:96px;height:54px" />
                        </a>
                    </td>

                }
            </tr>
        }

    </table>
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page, queryMonth = ViewBag.queryMonth }))
}