prjC349WebMVC/Controllers/RVIController.cs
using MySql.Data.MySqlClient;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;
using prjC349WebMVC.Models;
using System.Data;
using PagedList;
using NPOI.HSSF.UserModel;
using NPOI.SS.UserModel;
using NPOI.SS.Util;
using System.IO;
using NPOI.XSSF.UserModel;

namespace prjC349WebMVC.Controllers
{

    public class RVIController : Controller
    {
        string connStr = WebConfigurationManager.ConnectionStrings["c349ConnectionString"].ConnectionString;
        int pageSize = 10;
        public ActionResult Index(string queryMonth, int page = 1)
        {
            //if (queryMonth == null)
            //{
            //    queryMonth = DateTime.Now.Month.ToString().PadLeft(2,'0')+"/"+ DateTime.Now.Year.ToString();
            //}
            ViewBag.queryMonth = queryMonth;
            int currentPage = page < 1 ? 1 : page;
            var result = GetAllRecrods(queryMonth).ToPagedList(currentPage, pageSize);
            //ViewBag.Cookie = Request.Cookies.AllKeys[0];
            return View(result);
        }
        public ActionResult Create()
        {

            var selectList = new List<SelectListItem>()
            {
                new SelectListItem {Text="text-1", Value="value-1" },
                new SelectListItem {Text="text-2", Value="value-2" },
                new SelectListItem {Text="text-3", Value="value-3" },
            };

            //預設選擇哪一筆
            selectList.Where(q => q.Value == "value-2").First().Selected = true;

            ViewBag.SelectList = selectList;
            return View();
        }
        [HttpPost]
        public ActionResult Create(remote_visua_inspection remote_visua_inspection)
        {
            if (ModelState.IsValid)
            {
                ViewBag.Error = false;
                try
                {
                    MySqlCommand cmd = new MySqlCommand();
                    cmd.CommandText = "INSERT INTO remote_visua_inspection(tdate,carId,comment1,comment2,coil1,coil2,coil3,coil4,coil5,coil6,coil7,coil8,creator,updateTime,ip)" +
                        "VALUES(@tdate,@carId,@comment1,@comment2,@coil1,@coil2,@coil3,@coil4,@coil5,@coil6,@coil7,@coil8,@creator,@updateTime,@ip)";
                    //cmd.Parameters.Add(new MySqlParameter("@id", MySqlDbType.VarChar)).Value = employee.id;
                    cmd.Parameters.Add(new MySqlParameter("@tdate", MySqlDbType.Date)).Value = remote_visua_inspection.tdate;
                    cmd.Parameters.Add(new MySqlParameter("@carId", MySqlDbType.VarChar)).Value = remote_visua_inspection.carId;
                    cmd.Parameters.Add(new MySqlParameter("@comment1", MySqlDbType.VarChar)).Value = remote_visua_inspection.comment1;
                    cmd.Parameters.Add(new MySqlParameter("@comment2", MySqlDbType.VarChar)).Value = remote_visua_inspection.comment2;
                    cmd.Parameters.Add(new MySqlParameter("@coil1", MySqlDbType.VarChar)).Value = remote_visua_inspection.coil1;
                    cmd.Parameters.Add(new MySqlParameter("@coil2", MySqlDbType.VarChar)).Value = remote_visua_inspection.coil2;
                    cmd.Parameters.Add(new MySqlParameter("@coil3", MySqlDbType.VarChar)).Value = remote_visua_inspection.coil3;
                    cmd.Parameters.Add(new MySqlParameter("@coil4", MySqlDbType.VarChar)).Value = remote_visua_inspection.coil4;
                    cmd.Parameters.Add(new MySqlParameter("@coil5", MySqlDbType.VarChar)).Value = remote_visua_inspection.coil5;
                    cmd.Parameters.Add(new MySqlParameter("@coil6", MySqlDbType.VarChar)).Value = remote_visua_inspection.coil6;
                    cmd.Parameters.Add(new MySqlParameter("@coil7", MySqlDbType.VarChar)).Value = remote_visua_inspection.coil7;
                    cmd.Parameters.Add(new MySqlParameter("@coil8", MySqlDbType.VarChar)).Value = remote_visua_inspection.coil8;

                    if (IPAddress.Get() == "::1")
                    {
                        cmd.Parameters.Add(new MySqlParameter("@creator", MySqlDbType.VarChar)).Value = "test";
                    }
                    else
                    {
                        cmd.Parameters.Add(new MySqlParameter("@creator", MySqlDbType.VarChar)).Value = Request.Cookies["uid"].Value;
                    }
                    cmd.Parameters.Add(new MySqlParameter("@updateTime", MySqlDbType.Date)).Value = DateTime.Now;
                    cmd.Parameters.Add(new MySqlParameter("@ip", MySqlDbType.VarChar)).Value = IPAddress.Get();
                    ExecuteCmd(cmd);
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    ViewBag.Error = true;
                    return View(remote_visua_inspection);
                }
            }
            return View(remote_visua_inspection);
        }
        public ActionResult Edit(string id)
        {

            return View(GetRecrod(id));
        }
        [HttpPost]
        public ActionResult Edit(remote_visua_inspection remote_visua_inspection)
        {
            if (ModelState.IsValid)
            {
                MySqlCommand cmd = new MySqlCommand();

                cmd.CommandText = "UPDATE remote_visua_inspection SET tdate=@tdate, carId=@carId,comment1=@comment1, comment2=@comment2, " +
                    "coil1=@coil1, coil2=@coil2, coil3=@coil3, coil4=@coil4, coil5=@coil5, coil6=@coil6, coil7=@coil7 ,coil8=@coil8,updateTime=@updateTime WHERE id=@id";
                cmd.Parameters.Add(new MySqlParameter("@id", MySqlDbType.VarChar)).Value = remote_visua_inspection.id;
                cmd.Parameters.Add(new MySqlParameter("@tdate", MySqlDbType.Date)).Value = remote_visua_inspection.tdate;
                cmd.Parameters.Add(new MySqlParameter("@carId", MySqlDbType.VarChar)).Value = remote_visua_inspection.carId;
                cmd.Parameters.Add(new MySqlParameter("@comment1", MySqlDbType.VarChar)).Value = remote_visua_inspection.comment1;
                cmd.Parameters.Add(new MySqlParameter("@comment2", MySqlDbType.VarChar)).Value = remote_visua_inspection.comment2;
                cmd.Parameters.Add(new MySqlParameter("@coil1", MySqlDbType.VarChar)).Value = remote_visua_inspection.coil1;
                cmd.Parameters.Add(new MySqlParameter("@coil2", MySqlDbType.VarChar)).Value = remote_visua_inspection.coil2;
                cmd.Parameters.Add(new MySqlParameter("@coil3", MySqlDbType.VarChar)).Value = remote_visua_inspection.coil3;
                cmd.Parameters.Add(new MySqlParameter("@coil4", MySqlDbType.VarChar)).Value = remote_visua_inspection.coil4;
                cmd.Parameters.Add(new MySqlParameter("@coil5", MySqlDbType.VarChar)).Value = remote_visua_inspection.coil5;
                cmd.Parameters.Add(new MySqlParameter("@coil6", MySqlDbType.VarChar)).Value = remote_visua_inspection.coil6;
                cmd.Parameters.Add(new MySqlParameter("@coil7", MySqlDbType.VarChar)).Value = remote_visua_inspection.coil7;
                cmd.Parameters.Add(new MySqlParameter("@coil8", MySqlDbType.VarChar)).Value = remote_visua_inspection.coil8;
                cmd.Parameters.Add(new MySqlParameter("@updateTime", MySqlDbType.Date)).Value = DateTime.Now;
                cmd.Parameters.Add(new MySqlParameter("@ip", MySqlDbType.VarChar)).Value = IPAddress.Get();


                ExecuteCmd(cmd);
                return RedirectToAction("Index");
            }
            return View(remote_visua_inspection);
        }
        public ActionResult Delete(string id)
        {
            MySqlCommand cmd = new MySqlCommand();
            cmd.CommandText = "DELETE FROM remote_visua_inspection WHERE id=@id";
            cmd.Parameters.Add(new MySqlParameter("@id", MySqlDbType.VarChar)).Value = id;

            ExecuteCmd(cmd);
            return RedirectToAction("Index");
        }
        // GET: Home
        private List<remote_visua_inspection> GetAllRecrods(string queryMonth)
        {
            MySqlConnection conn = new MySqlConnection(connStr);
            conn.ConnectionString = connStr;
            string SQL = "";
            if (queryMonth == "" || queryMonth == null)
            {
                SQL = $"SELECT * FROM remote_visua_inspection ORDER BY id DESC";
            }
            else
            {
                SQL = $"SELECT * FROM remote_visua_inspection WHERE MONTH(tdate) = {DateTime.Parse(queryMonth).Month} AND YEAR(tdate) = {DateTime.Parse(queryMonth).Year} ORDER BY id DESC";
            }
            MySqlDataAdapter adp = new MySqlDataAdapter(SQL, conn);
            DataSet ds = new DataSet();
            adp.Fill(ds);
            DataTable dt = ds.Tables[0];
            List<remote_visua_inspection> employees = new List<remote_visua_inspection>();
            for (int i = 0; i < dt.Rows.Count; i++)
            {
                employees.Add(new remote_visua_inspection
                {
                    id = dt.Rows[i]["id"].ToString(),
                    tdate = DateTime.Parse(dt.Rows[i]["tdate"].ToString()),
                    carId = dt.Rows[i]["carId"].ToString(),
                    comment1 = dt.Rows[i]["comment1"].ToString(),
                    comment2 = dt.Rows[i]["comment2"].ToString(),
                    coil1 = dt.Rows[i]["coil1"].ToString(),
                    coil2 = dt.Rows[i]["coil2"].ToString(),
                    coil3 = dt.Rows[i]["coil3"].ToString(),
                    coil4 = dt.Rows[i]["coil4"].ToString(),
                    coil5 = dt.Rows[i]["coil5"].ToString(),
                    coil6 = dt.Rows[i]["coil6"].ToString(),
                    coil7 = dt.Rows[i]["coil7"].ToString(),
                    coil8 = dt.Rows[i]["coil8"].ToString(),
                    creator = dt.Rows[i]["creator"].ToString(),
                    updateTime = DateTime.Parse(dt.Rows[i]["updateTime"].ToString()),
                    ip = dt.Rows[i]["ip"].ToString()

prjC349WebMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/vue.js"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            @Html.ActionLink("C349WebMVC", "Index", "RVI", new { area = "" }, new { @class = "navbar-brand" })
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                @{
                    try
                    {
                        if (Request.Cookies["name"].Value != null)
                        {
                            <label>您好,@Server.UrlDecode(Request.Cookies["name"].Value)</label>
                        }
                    }
                    catch
                    {
                        <label> 尚未登入EIP </label>
                        <a href="https://eip.csc.com.tw/SSO/DSS0/DSAOS0.aspx" target="_blank"> 登入 </a>
                    }
                }
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                    @{
                        try
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    C34工廠日誌
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li class="nav-item">
                                        <a href="http://dept.csc.com.tw/MIS/C34/C34Web/C34X.aspx" target="_blank" class="dropdown-item">C34工廠日誌</a>
                                    </li>
                                </ul>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    LiveUpdateOY07
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li class="nav-item">@Html.ActionLink("LiveUpdateOY07", "LiveUpdateOY07", "Toolbox", new { }, new { @class = "dropdown-item" })</li>
                                </ul>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    AdvanceOY15
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li class="nav-item">@Html.ActionLink("包裝線排程", "Y5PIS_Schedule", "Toolbox", new { }, new { @class = "dropdown-item" })</li>
                                    <li class="nav-item">@Html.ActionLink("AdvanceOY15", "AdvanceOY15", "Toolbox", new { }, new { @class = "dropdown-item" })</li>
                                    <li class="nav-item">@Html.ActionLink("清雜區_中控", "AdvanceOY15ClearMixAreaAdmin", "Toolbox", new { }, new { @class = "dropdown-item" })</li>
                                    <li class="nav-item">@Html.ActionLink("清雜區_天車手", "AdvanceOY15ClearMixAreaCraneOperator", "Toolbox", new { }, new { @class = "dropdown-item" })</li>
                                </ul>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    遠端檢放
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li class="nav-item">@Html.ActionLink("遠端檢放", "Index", "RVI_CreateWithEPSLOG", new { }, new { @class = "dropdown-item" })</li>
                                </ul>
                            </li>
                        }
                        catch { }
                    }



                    <!--<li class="nav-item">
                        @*<a class="nav-link active" aria-current="page" href="#">Article</a>*@
                    <!--</li>-->
                    @*<li class="nav-item">
                            @Html.ActionLink("員工管理", "Index", "Home", "", new { @class = "av-link active" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("文章管理", "Index", "Article", "", new { @class = "av-link active" })
                        </li>*@
                    @*<li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                員工管理
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li>@Html.ActionLink("員工管理", "Index", "Home", new { }, new { @class = "dropdown-item" })</li>
                                <li>@Html.ActionLink("員工新增", "Create", "Home", new { }, new { @class = "dropdown-item" })</li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" href="#">Something else here</a></li>
                            </ul>
                        </li>*@
                    @*<li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                文章管理
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li>@Html.ActionLink("文章管理", "Index", "Article", new { }, new { @class = "dropdown-item" })</li>
                                <li>@Html.ActionLink("文章新增", "Create", "Article", new { }, new { @class = "dropdown-item" })</li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" href="#">Something else here</a></li>
                            </ul>
                        </li>*@
                    @*<li class="nav-item">
                            <a class="nav-link disabled">Disabled</a>
                        </li>*@
                </ul>

                @*<form class="d-flex">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success" type="submit">Search</button>
                    </form>*@

            </div>
        </div>
    </nav>

    <div class="body-content">

        @RenderBody()
        @*@RenderSection("Validation", false)*@
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - C349WebMVC</p>
        </footer>
    </div>


    @RenderSection("scripts", false)


</body>
</html>